"""add lots and realized pnl

Revision ID: 4a2f1f452013
Revises: f72233994e27
Create Date: 2026-01-31 01:56:59.927617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2f1f452013'
down_revision: Union[str, Sequence[str], None] = 'f72233994e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('realized_pnl', sa.Float(), nullable=False))
    op.add_column('trades', sa.Column('realized_pnl_pct', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'realized_pnl_pct')
    op.drop_column('trades', 'realized_pnl')
    # ### end Alembic commands ###
